config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :conversations
      resources :messages
      resources :payments
      resources :products
      resources :reviews
      resources :stores

      root to: "stores#index"
    end
  resources :payments
  resources :reviews
  resources :products
  resources :stores
  devise_for :users

  root to: "stores#index"

  get "/vendor" => "stores#vendor"
  get "/support" => "stores#support"
  get "/brand" => "stores#brand"
  get "/dispensary" => "stores#dispensary"
  get "/delivery" => "stores#delivery"
  get "/service" => "stores#service"
  get '/search' => "stores#search"
  get '/store_created' => "stores#store_created"

  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews
  has_many :products

  mount_uploader :image, ImageUploader
  mount_uploader :thumb, ThumbUploader

  def full_address
    [:address, :city, :state, :country].compact.join(', ')
  end

  geocoded_by :full_address

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def self.search(search)
    if search
      self.where('name LIKE ?', "%#{search}%")
    else
      self.all
    end
  end

end

app/controllers/admin/stores_controller.rb
module Admin
  class StoresController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Store.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Store.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :store_params, only: [:edit, :update]

  def index
    @store = Store.where(approval: "true")

    @rating = Review.all

    @search= Store.search(params[:search]) if params[:search].present?
  end

  def support
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                         .find(session[:conversations])
  end

  def vendor
    @tier = Payment.new
  end

  def dispensary
    @store = Store.where(store_type: "dispensary")
  end

  def delivery
    @store = Store.where(store_type: "delivery")
  end

  def brand
    @store = Store.where(store_type: "brand")
  end

  def service
    @store = Store.where(store_type: "service")
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(params.required(:store).permit(
                                                  :name, :website, :email,
                                                  :address, :city, :state, :zip, :country,
                                                  :phone_1,
                                                  :description,
                                                  :image, :thumb,
                                                  :mon_open, :mon_end, :mon_closed,
                                                  :tues_open, :tues_end, :tues_closed,
                                                  :wed_open, :wed_end, :wed_closed,
                                                  :thurs_open, :thurs_end, :thurs_closed,
                                                  :fri_open, :fri_end, :fri_closed,
                                                  :sat_open, :sat_end, :sat_closed,
                                                  :sun_open, :sun_end, :sun_closed))

    @store.user_id = current_user.id

    @coord = [@store.address, @store.city, @store.state, @store.zip, @store.country].compact.join(', ')
    results = Geocoder.search(@coord)
    @store.latitude = results.first.latitude
    @store.longitude = results.first.longitude

    gibbon = Gibbon::Request.new(api_key: ENV["MAILCHIMP_API_KEY"])
    gibbon.lists(ENV["MAILCHIMP_LIST_ID"]).members.create(body: {email_address: @store.email, status: "subscribed", merge_fields: {FNAME: @store.name}})

    if @store.save!
      redirect_to store_created_path
    else
      render :new
    end
  end

  def edit
    @item = Product.new
  end

  def update
    if @store.update(params.required(:store).permit(
        :name, :website, :email,
        :address, :city, :state, :zip, :country,
        :area_code, :phone_1, :phone_2,
        :description,
        :image, :thumb,
        :mon_open, :mon_end, :mon_closed,
        :tues_open, :tues_end, :tues_closed,
        :wed_open, :wed_end, :wed_closed,
        :thurs_open, :thurs_end, :thurs_closed,
        :fri_open, :fri_end, :fri_closed,
        :sat_open, :sat_end, :sat_closed,
        :sun_open, :sun_end, :sun_closed))
      redirect_to @store
    else
      render :edit
    end
  end

  def show
    @store = Store.find(params[:id])

    @review = Review.new
    @item = Product.new
  end

  private

  def store_params
    @store = Store.find(params[:id])
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= simple_form_for(@store, html: { class: 'form-inline' }) do |f| %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <form role="form">
        <div class="form-group">
          <%= f.input :name %>
        </div>
        <div class="form-group">
          <%= f.input :address %>
          <%= f.input :city %>
          <%= f.input :state %>
          <%= f.input :zip %>
        </div>
        <div class="form-group">
          <%= f.input :area_code %>
          <%= f.input :phone_1 %>
          <%= f.input :phone_2 %>
        </div>
        <div class="form-group">
          <%= f.input :description %>
        </div>
        <div class="form-group">
          <%= f.input :image %>
        </div>
        <h2>
          Store Hours
        </h2>
        <form role="form" class="form-inline">
          <div class="form-group">
            <div class="form-group form-hours">
              <%= f.label :mon_open, class: "col-sm-2 control-label" %>
              <%= f.time_select :mon_open, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="form-group form-hours">
              <%= f.label :mon_end, class: "col-sm-2 control-label" %>
              <%= f.time_select :mon_end, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="checkbox form-hours">
              <%= f.input :mon_closed %>
            </div>
          </div>
          <div class="form-group">
            <div class="form-group form-hours">
              <%= f.label :tues_open, class: "col-sm-2 control-label" %>
              <%= f.time_select :tues_open, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="form-group form-hours">
              <%= f.label :tues_end, class: "col-sm-2 control-label" %>
              <%= f.time_select :tues_end, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="checkbox form-hours">
              <%= f.input :tues_closed %>
            </div>
          </div>
          <div class="form-group">
            <div class="form-group form-hours">
              <%= f.label :wed_open, class: "col-sm-2 control-label" %>
              <%= f.time_select :wed_open, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="form-group form-hours">
              <%= f.label :wed_end, class: "col-sm-2 control-label" %>
              <%= f.time_select :wed_end, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="checkbox form-hours">
              <%= f.input :wed_closed %>
            </div>
          </div>
          <div class="form-group">
            <div class="form-group form-hours">
              <%= f.label :thurs_open, class: "col-sm-2 control-label" %>
              <%= f.time_select :thurs_open, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="form-group form-hours">
              <%= f.label :thurs_end, class: "col-sm-2 control-label" %>
              <%= f.time_select :thurs_end, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="checkbox form-hours">
              <%= f.input :thurs_closed %>
            </div>
          </div>
          <div class="form-group">
            <div class="form-group form-hours">
              <%= f.label :fri_open, class: "col-sm-2 control-label" %>
              <%= f.time_select :fri_open, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="form-group form-hours">
              <%= f.label :fri_end, class: "col-sm-2 control-label" %>
              <%= f.time_select :fri_end, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="checkbox form-hours">
              <%= f.input :fri_closed %>
            </div>
          </div>
          <div class="form-group">
            <div class="form-group form-hours">
              <%= f.label :sat_open, class: "col-sm-2 control-label" %>
              <%= f.time_select :sat_open, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="form-group form-hours">
              <%= f.label :sat_end, class: "col-sm-2 control-label" %>
              <%= f.time_select :sat_end, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="checkbox form-hours">
              <%= f.input :sat_closed %>
            </div>
          </div>
          <div class="form-group">
            <div class="form-group form-hours">
              <%= f.label :sun_open, class: "col-sm-2 control-label" %>
              <%= f.time_select :sun_open, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="form-group form-hours">
              <%= f.label :sun_end, class: "col-sm-2 control-label" %>
              <%= f.time_select :sun_end, {minute_step: 30}, class: "form-control date" %>
            </div>
            <div class="checkbox form-hours">
              <%= f.input :sun_closed %>
            </div>
          </div>
        </form>
        <button type="submit" class="btn btn-primary">
          Submit
        </button>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/stores/_new_product.html.erb
<%= simple_form_for(@item, html: { class: 'form-inline' }) do |f|%>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <form role="form">
          <div class="form-group">
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :price %>

            <%= f.submit %>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/stores/_search.html.erb
<%= form_tag stores_path, :method => 'get' do %>
  <div class="text-center">
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  </div>
<% end %>

<% if @search.present? %>
  <div class="flexslider">
    <ul class="slides">
      <% for p in @search %>
        <li class="slide">
          <%= link_to p.name, store_path(p) %>
          <br>
          <%= p.city %>, <%= p.state %>
          <br>
          <p>````</p>
          <br>
          <p>````</p>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/stores/_support.html.erb
<% session[:conversations] ||= [] %>

<% @users = User.where(id: 2) %>

<% @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations]) %>

<div class="row">
  <div class="support support-link">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="panel-body support-link">
    <%= link_to (octicon "comment", :height => 35), conversations_path(@users), remote: true, method: :post %>
  </div>
</div>

app/views/stores/brand.html.erb
<% @store.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |p| %>
      <div class='col-md-3'>
        <p>
          <% if p.thumb.url %>
            <%= image_tag p.thumb.url %>
          <% end %>
        </p>
        <h3 class="text-center">
          <%= link_to p.name, stores_path(p) %>
        </h3>
        <p class="text-center">
          <%= p.city %>, <%= p.state %>
        </p>
        <p class="text-center">
          <%= p.description %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/stores/delivery.html.erb
<% @store.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |p| %>
      <div class='col-md-3'>
        <p>
          <% if p.thumb.url %>
            <%= image_tag p.thumb.url %>
          <% end %>
        </p>
        <h3 class="text-center">
          <%= link_to p.name, stores_path(p) %>
        </h3>
        <p class="text-center">
          <%= p.city %>, <%= p.state %>
        </p>
        <p class="text-center">
          <%= p.description %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/stores/dispensary.html.erb
<% @store.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |p| %>
      <div class='col-md-3'>
        <p>
          <% if p.thumb.url %>
            <%= image_tag p.thumb.url %>
          <% end %>
        </p>
        <h3 class="text-center">
          <%= link_to p.name, stores_path(p) %>
        </h3>
        <p class="text-center">
          <%= p.city %>, <%= p.state %>
        </p>
        <p class="text-center">
          <%= p.description %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<%= render 'stores/partials/form' %>

<div class="new-product-heading">
  <h3 class="text-center">
    Add Product
  </h3>
</div>
<div class="row">
  <div class="store-product">
    <div class="col-md-4">
      <p><b>Product Name</b></p>
    </div>
    <div class="col-md-5">
      <p><b>Description</b></p>
    </div>
    <div class="col-md-3">
      <p><b>Price</b></p>
    </div>
  </div>
</div>
<% product = Product.where(:store_id => @store.id) %>
<% product.each do |f| %>
  <div class="row">
    <div class="store-product">

      <div class="col-md-4">
        <%= f.name %>
      </div>
      <div class="col-md-5">
        <%= f.description %>
      </div>
      <div class="col-md-3">
        <%= f.price %>
      </div>
    </div>
  </div>
<% end %>

<%= bootstrap_form_for(@item, local: true) do |f|%>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <form role="form">
          <div class="form-group">
            <%= f.text_field :name %>
            <%= f.text_area :description %>
            <%= f.file_field :image %>
            <%= f.text_field :price %>
            <%= f.hidden_field :store_id, :value => @store.id %>

            <%= f.submit %>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/stores/index.html.erb
<div class="container-fluid p-0">
  <div class="row img">
    <div class="col-md-12">
      <div class="index-heading">
        <h1 class="text-center index-heading-text">
          World’s Premier Cannabis Marketplace
        </h1>
        <p class="text-center index-heading-text">NuggPlug is the Safest, most convienient 420-platform that offers our users access top hundreds of the top Cannabis brands in the world</p>
        <p class="text-center index-heading-text"> We only list 100% trusted, verified businesses in the worldwide Cannabis industry to ensure that all of our members recieve nothing but the highest quality</p>
      </div>
      <div class="type-header">
      <%= render "stores/search" %>
      </div>
      <div class="type-header">
        <hr class="vendor-hr">
        <h1 class="text-center">
          Featured Brands
        </h1>
        <p class="text-center">
          Check out our latest Cannabis brands and top choices from our 420 experts
        </p>
        <hr class="vendor-hr">
      </div>
        <div class="flexslider">
        <ul class="slides">
          <% @store.each do |p| %>
            <li class="slide text-center">
              <% if p.thumb.url %>
                <%= image_tag p.thumb.url %>
              <% end %>
              <h3>
                <%= link_to p.name, store_path(p) %>
              </h3>
              <br>
              <h4>
                <%= p.store_type %>
              </h4>
              <br>
              <h4>
                <p><%= p.city %>, <%= p.state %></p>
              </h4>
            </li>
          <% end %>
        </ul>
      </div>
      <h3 class="text-center vendor-header">
        <%= link_to "Advertise your business on NuggPlug!", vendor_path, :class => "b2" %>
      </h3>
      <div class="type-header">
        <hr class="vendor-hr">
        <h1 class="text-center">
          Dispensaries
        </h1>
        <hr class="vendor-hr">
      </div>
      <div class="flexslider">
        <ul class="slides text-center">
          <% disp = @store.where(:store_type => "dispensary") %>
          <% disp.each do |p| %>
            <li class="slide">
              <% if p.thumb.url %>
                <%= image_tag p.thumb.url %>
              <% end %>
              <h3>
                <%= link_to p.name, store_path(p) %>
              </h3>
              <br>
              <h4>
                <p><%= p.city %>, <%= p.state %></p>
              </h4>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="type-header">
        <hr class="vendor-hr">
        <h1 class="text-center">
          Delivery Services
        </h1>
        <hr class="vendor-hr">
      </div>
      <div class="flexslider">
        <ul class="slides text-center">
          <% del = @store.where(:store_type => "delivery") %>
          <% del.each do |p| %>
            <li class="slide">
              <% if p.thumb.url %>
                <%= image_tag p.thumb.url %>
              <% end %>
              <h3>
                <%= link_to p.name, store_path(p) %>
              </h3>
              <br>
              <h4>
                <p><%= p.city %>, <%= p.state %></p>
              </h4>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="questions text-center">
        <h2>
          Do you have questions?  Get in touch.
        </h2>
      </div>
    </div>
  </div>
</div>

app/views/stores/new.html.erb
<%= render "stores/partials/form" %>

app/views/stores/show.html.erb
<div class="container-fluid show-container">
  <div class="row">
    <div class="col-md-12">
      <ul class="flex-container">
        <div class="flex-item">
          <div class="flex-item show-header" style="background-image: url(<%= asset_url(@store.image)%>); background-repeat: no-repeat; background-position: center; background-size: cover">
            <h2 class="text-center">
              <%= @store.name %>
            </h2>
            <ul class="header-flex-container space-around">
              <h5 class="flex-item store-header-text">
                <%= octicon "device-mobile", :height => 15,  :class => "right left", :"aria-label" => "hi" %> <%= number_to_phone(@store.phone_1) %>
              </h5>
              <li class="flex-item store-header-text">
                <h5 class="text-right">
                  <%= @store.website %>
                </h5>
              </li>
              <li class="flex-item store-header-text">
                <h5 class="text-right">
                  <%= social_share_button_tag('Check out this store!', :url => store_path(@store), desc: @store.name) %>
                </h5>
              </li>
            </ul>
              <p class="flex-item">
                <% if user_signed_in? %>
                 <% if current_user.id == @store.user_id %>
                  <%= link_to "edit store", edit_store_path(@store) %>
                <% end %>
                <% end %>
              </p>
            </div>
          </div>
        </ul>
      </ul>
    </div>
  </div>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <ul class="flex-container column">
        <div class="flex-item">
          <div class="show-desc">
            <%= @store.description %>
          </div>
        </div>
        <div class="flex-item show-items">
          <%= render "stores/partials/products" %>
        </div>
        <div class="flex-item">
          <div class="show-reviews">
            <%= render "stores/partials/reviews" %>
          </div>
        </div>
      </ul>
    </div>
    <div class="col-md-4">
      <ul class="flex-container column">
        <div class="flex-item">
          <div class="show-address">
            <h4>
              <%= @store.address%>
            </h4>
            <h4>
              <%= @store.city %> <%= @store.state %>, <%= @store.zip %>
            </h4>
          </div>
        </div>
        <div class="flex-item">
          <div class="show-open">
            <%= render "stores/partials/store_hours" %>
          </div>
        </div>
        <div class="flex-item">
          <div class="show-reviews">
            <div class="show-map">
              <% @coord = [@store.address, @store.city, @store.state, @store.zip, @store.country].compact.join(', ')%>
              <% results = Geocoder.search(@coord) %>
              <% @lat = results.first.latitude %>
              <% @lng = results.first.longitude %>

              <div style='width: 400px;'>
                <div id="map" style='width: 320px; height: 320px;'></div>
              </div>

              <script type="text/javascript">

                  handler = Gmaps.build('Google');

                  var lat = '<%= @lat %>'
                  var lng = '<%= @lng %>'

                  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                      markers = handler.addMarkers([
                          {
                              "lat": lat,
                              "lng": lng,
                              "picture": {
                                  "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
                                  "width":  32,
                                  "height": 32
                              },
                              "infowindow": "hello!"
                          }
                      ]);
                      handler.bounds.extendWith(markers);
                      handler.fitMapToBounds();
                  });
              </script>

            </div>
          </div>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/stores/store_created.html.erb
<h2 class="new-product-heading text-center">
  Thank you for your submission!
</h2>
<h4 class="text-center">
  Your store has been submitted for approval.
</h4>
<h4 class="text-center">
  This process generally takes 24-48 hours, thank you for your patience.
</h4>

app/views/stores/support.html.erb
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/stores/vendor.html.erb
<div class="container-fluid vendor-container">
  <div class="row">
    <div class="col-md-12">
      <ul class="flex-container">
        <div class="flex-item">
          <div class="vendor-header">
            <h2 class="flex-item text-center vendor-header-text">
              Join our online community
            </h2>
            <p class="text-center vendor-header-text">
              We started NuggPlug to bring together cannabis enthusiasts from around the world through a safe, secure platform. Whether you are a patient, recreational user or 420-friendly business or grower, we want you to be a NuggPlug member!
            </p>
          </div>
          <div class="vendor-body text-center">
            <h2>
              How it Works
            </h2>
            <hr class="vendor-hr">
            <p>
              Our 3-step process makes it incredibly easy to get more eyes on your 420 brand
            </p>
          </div>
          <div class="header-flex-container space-around vendor-body">
            <div class="col-sm-4 text-center vendor-card">
              <div class="vendor-icon">
                <%= octicon "zap", :height => 55,  :class => "right left", :"aria-label" => "hi" %>
              </div>
              <h4>
                Sign Up
              </h4>
              <p>
                Register for your NuggPlug account
              </p>
            </div>
            <div class="col-sm-4 text-center vendor-card">
              <div class="vendor-icon">
                <%= octicon "location", :height => 55,  :class => "right left", :"aria-label" => "hi" %>
              </div>
              <h4>
                Make a Listing
              </h4>
              <p>
                Our easy-to-use listing service takes just minutes
              </p>
            </div>
            <div class="col-sm-4 text-center vendor-card">
              <div class="vendor-icon">
                <%= octicon "smiley", :height => 55,  :class => "right left", :"aria-label" => "hi" %>
              </div>
              <h4>
                Generate Clients
              </h4>
              <p>
                People from around the world can now see your business
              </p>
            </div>
          </div>
          <div class="vendor-body text-center ">
            <td>
              <% if user_signed_in? %>
                <%= link_to "Join Today!", new_store_path, :class => "b1" %>
              <% else %>
                <%= link_to "Join Today!", new_user_session_path, :class => "b1" %>
              <% end %>
            </td>
            <h4 class="vendor-membership trial">
              Enjoy a free, no obligation 30 day trial.
            </h4>
          </div>
          <div class="vendor-body text-center ">
            <h2>
              Our Flexible Membership Packages
            </h2>
            <hr class="vendor-hr">
            <p class="vendor-membership">
              To meet the needs of all our Cannabis industry partners, we have developed three unique membership packages.
            </p>
            <%= render "stores/partials/packages" %>
          </div>
        </div>
      </ul>
    </div>
  </div>
</div>