config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :conversations
      resources :messages
      resources :payments
      resources :products
      resources :reviews
      resources :stores

      root to: "stores#index"
    end
  resources :payments
  resources :reviews
  resources :products
  resources :stores
  devise_for :users

  root to: "stores#index"

  get "/vendor" => "stores#vendor"
  get "/support" => "stores#support"
  get "/brand" => "stores#brand"
  get "/dispensary" => "stores#dispensary"
  get "/delivery" => "stores#delivery"
  get "/service" => "stores#service"
  get '/search' => "stores#search"
  get '/store_created' => "stores#store_created"

  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue pt-4 foot-fixed">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left footer">

    <!-- Grid row -->
    <div class="row">
      <div class="text-center">
        <h5>© Nugg Plug 2014-2019 / All rights reserved.</h5>
      </div>

      <div class="text-right">
        <%= link_to "Contact" %>
        <%= link_to "Support", support_path %>
      </div>
    </div>
  </div>

</footer>

app/views/shared/_nav.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-header">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse text-dark" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav ">
            <li class="nav-image">
              <%= link_to image_tag("nugg-plug-nav.png"), stores_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li class="nav-link">
              <%= link_to "All Stores", stores_path %>
            </li>
            <li class="nav-link">
              <%= link_to "Brands", brand_path %>
            </li>
            <li class="nav-link">
              <%= link_to "Dispensary", dispensary_path %>
            </li>
            <li class="nav-link">
              <%= link_to "Delivery", delivery_path %>
            </li>
            <li class="nav-link">
              <%= link_to "Services", service_path %>
            </li>
            <% if user_signed_in? %>
              <% if current_user.user_type == 'admin' %>
                <li class="nav-link">
                  <%= link_to "Admin Dashboard", admin_root_path %>
                </li>
              <% end %>
              <li class="dropdown">
                <a id="drop4" role="button" data-toggle="dropdown" href="#" class="navbar-icons">
                  <%= octicon "person", :height => 15,  :class => "right left", :"aria-label" => "hi" %>
                <b class="caret"></b></a>
                <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                  <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="#">
                    <li><%= link_to('My Account', edit_user_registration_path) %></li>
                    </a>
                  </li>
                  <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="#">
                  <li><%= link_to('My Store', edit_user_registration_path) %></li>
                    </a>
                  </li>
                  <li role="presentation">
                    <% @stores = Store.where(:user_id => current_user.id) %>
                    <% @stores.each do |f| %>
                      <a role="menuitem" tabindex="-1" href="#">
                        <%= link_to f.name, store_path(f) %>
                      </a>
                    <% end %>
                    </a>
                  </li>
                  <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="#">
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                    </a>
                  </li>
                </ul>
              </li>
            <% else %>
              <li class="nav-link">
                <%= link_to('Sign in', new_user_session_path) %>
              </li>
              <li class="nav-link">
                <%= link_to('Sign up', new_user_registration_path) %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>